on:
  push:
    branches:
    - main
    paths:
    - '*.troff'
    - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - name: Instal groff
      run: |
        sudo apt-get update
        sudo apt-get install -y groff
    - name: Update README
      run: groff -man -Thtml man.troff > README.md
    - uses: stefanzweifel/git-auto-commit-action@v5
