on:
  push:
    branches:
    - main
    paths:
    - '*.troff'
    - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - name: Install groff
      run: |
        sudo apt-get update
        sudo apt-get install -y groff
    - name: Update README
      run: |
        echo '```text' > README.md
        groff -man -Tascii man.troff | sed -E 's/\x1B\[[0-9;]*m//g' >> README.md
        echo '```' >> README.md
    - uses: stefanzweifel/git-auto-commit-action@v5
